---
version: 1

package:
  types:
    max: 10
  exported_funcs:
    max: 20
  unexported_funcs:
    max: 35
  efferent:
    max: 11
  afferent:
    max: 12
  metrics:
    distance:
      max: 0.70

type:
  fields:
    max: 14
  methods:
    max: 5
  metrics:
    amc:
      max: 4
    lcom1:
      max: 5
    lcom96b:
      max: 0.70
    camc:
      min: 0.30
    tcc:
      min: 0.70
    cbo:
      max: 4
    reusability:
      min: 0.35
