package goloader

import (
	"context"
	"errors"
	"fmt"
	"go/ast"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mostafakhairy0305-dot/go-modularity/internal/features/typefacts/domain"
	"github.com/mostafakhairy0305-dot/go-modularity/internal/features/typefacts/ports/outbound"
	"golang.org/x/tools/go/packages"
)

func writeModule(t *testing.T, files map[string]string) string {
	t.Helper()

	dir := t.TempDir()
	if err := os.WriteFile(
		filepath.Join(dir, "go.mod"),
		[]byte("module example.com/cov\n\ngo 1.22\n"),
		0o600,
	); err != nil {
		t.Fatal(err)
	}
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}

	return dir
}

func TestExtractRichTypeShapes(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"shapes/shapes.go": `
package shapes

type Other struct{}

type Closer interface{ Close() }

type Holder struct {
	Ptr   *Other
	List  []Other
	Dict  map[Other]Other
	Fn    func(Other) Other
	Anon  struct{ Nested *Other }
	Iface interface {
		Closer
		Do(Other) Other
	}
}

func Helper() {}

type Alias = Other

const Const = 1

var _ = Const

func (h *Holder) Use() {}
`,
		"shapes/gen.go": `// Code generated by tool. DO NOT EDIT.

package shapes

type Generated struct{ X int }

func (g *Generated) Run() {}
`,
		"iface/iface.go": `
package iface

type Speaker interface {
	Speak()
}

type Talker int

func (Talker) Speak() {}
`,
	})

	mod, pkgs, err := load(context.Background(), outbound.FactOptions{
		Directory:        dir,
		Patterns:         nil, // exercises ./... default
		IncludeGenerated: true,
		BuildTags:        []string{"ignoretag"},
	})
	if err != nil {
		t.Fatal(err)
	}
	if mod != "example.com/cov" {
		t.Fatalf("module = %q", mod)
	}

	foundGen := false
	foundHolder := false
	for _, pkg := range pkgs {
		if !strings.HasSuffix(pkg.Path, "/shapes") {
			continue
		}
		for _, te := range pkg.Types {
			switch te.Name {
			case "Generated":
				foundGen = true
			case "Holder":
				foundHolder = true
				if len(te.ReferencedTypeKeys) == 0 {
					t.Fatalf("Holder refs empty: %v", te.ReferencedTypeKeys)
				}
			}
		}
	}
	if !foundHolder {
		t.Fatal("Holder not extracted")
	}
	if !foundGen {
		t.Fatal("Generated type missing with IncludeGenerated=true")
	}

	_, pkgs2, err := load(context.Background(), outbound.FactOptions{
		Directory: dir,
		Patterns:  []string{"./shapes"},
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, pkg := range pkgs2 {
		for _, te := range pkg.Types {
			if te.Name == "Generated" {
				t.Fatal("Generated should be skipped when IncludeGenerated=false")
			}
		}
	}

	// Interface method with no body hits walkBody's nil-body path.
	for _, pkg := range pkgs {
		if !strings.HasSuffix(pkg.Path, "/iface") {
			continue
		}
		for _, te := range pkg.Types {
			if te.Name == "Talker" && len(te.Methods) != 1 {
				t.Fatalf("Talker methods = %d", len(te.Methods))
			}
		}
	}
}

func TestFieldDocumentedAndSkipPos(t *testing.T) {
	if fieldDocumented(nil, token.Pos(1)) {
		t.Fatal("empty fieldDocs should be false")
	}
	docs := []docRange{{start: 10, end: 20, documented: true}}
	if fieldDocumented(docs, token.Pos(5)) {
		t.Fatal("pos before first range should be false")
	}
	if !fieldDocumented(docs, token.Pos(15)) {
		t.Fatal("pos inside documented range should be true")
	}

	fset := token.NewFileSet()
	f := fset.AddFile("gen.go", -1, 20)
	f.SetLinesForContent([]byte("package x\n"))
	if skipPos(fset, true, map[string]bool{f.Name(): true}, token.Pos(f.Base())) {
		t.Fatal("includeGenerated=true must not skip")
	}
}

func TestSelectPackagesTruncation(t *testing.T) {
	loaded := make([]*packages.Package, 0, 12)
	for i := 0; i < 12; i++ {
		loaded = append(loaded, &packages.Package{
			PkgPath: fmt.Sprintf("m/p%d", i),
			Errors:  []packages.Error{{Msg: "boom"}},
		})
	}
	_, err := selectPackages(loaded, false)
	if err == nil || !strings.Contains(err.Error(), "and 2 more") {
		t.Fatalf("truncation error = %v", err)
	}
}

func TestResolveBaseDirFailures(t *testing.T) {
	origGetwd, origAbs := osGetwd, filepathAbs
	t.Cleanup(func() { osGetwd, filepathAbs = origGetwd, origAbs })

	osGetwd = func() (string, error) { return "", errors.New("no cwd") }
	if got := resolveBaseDir(""); got != "" {
		t.Fatalf("getwd failure = %q, want empty", got)
	}

	filepathAbs = func(string) (string, error) { return "", errors.New("no abs") }
	if got := resolveBaseDir("relative"); got != "relative" {
		t.Fatalf("abs failure = %q, want relative", got)
	}
}

func TestLoadPackagesSeamErrors(t *testing.T) {
	orig := packagesLoad
	t.Cleanup(func() { packagesLoad = orig })

	sentinel := errors.New("load boom")
	packagesLoad = func(*packages.Config, ...string) ([]*packages.Package, error) {
		return nil, sentinel
	}
	if _, err := loadPackages(
		context.Background(),
		outbound.FactOptions{Patterns: []string{"./"}},
	); !errors.Is(
		err,
		sentinel,
	) {
		t.Fatalf("load error = %v", err)
	}

	packagesLoad = func(*packages.Config, ...string) ([]*packages.Package, error) {
		return nil, nil
	}
	if _, err := loadPackages(
		context.Background(),
		outbound.FactOptions{Patterns: []string{"./x"}},
	); err == nil ||
		!strings.Contains(err.Error(), "no packages matched") {
		t.Fatalf("empty load = %v", err)
	}

	packagesLoad = func(*packages.Config, ...string) ([]*packages.Package, error) {
		return []*packages.Package{{
			PkgPath: "m/broken",
			Errors:  []packages.Error{{Msg: "x"}},
		}}, nil
	}
	if _, err := loadPackages(context.Background(), outbound.FactOptions{
		Patterns: []string{"./x"}, ContinueOnError: true,
	}); err == nil || !strings.Contains(err.Error(), "no loadable packages") {
		t.Fatalf("no loadable = %v", err)
	}
}

func TestExtractAllWorkerError(t *testing.T) {
	orig := runExtractWorkers
	t.Cleanup(func() { runExtractWorkers = orig })

	sentinel := errors.New("extract failed")
	runExtractWorkers = func(context.Context, int, int, func(int) error) error {
		return sentinel
	}

	pkg := healthy("m/a", "a.go")
	_, err := extractAll(
		context.Background(),
		[]*packages.Package{pkg},
		outbound.FactOptions{},
		"m",
	)
	if !errors.Is(err, sentinel) {
		t.Fatalf("extractAll = %v", err)
	}

	packagesLoadOrig := packagesLoad
	t.Cleanup(func() { packagesLoad = packagesLoadOrig })
	packagesLoad = func(*packages.Config, ...string) ([]*packages.Package, error) {
		return []*packages.Package{healthy("m/a", "a.go")}, nil
	}
	_, _, err = load(context.Background(), outbound.FactOptions{Patterns: []string{"./a"}})
	if !errors.Is(err, sentinel) {
		t.Fatalf("load extract error = %v", err)
	}
}

func TestWalkBodyNilBody(t *testing.T) {
	var facts domain.MethodFacts
	walkBody(nil, &ast.FuncDecl{}, nil, 0, nil, nil, &facts)
}

func TestIndexTypeDeclSkipsNonTypeSpec(t *testing.T) {
	decl := &ast.GenDecl{
		Tok:   token.TYPE,
		Specs: []ast.Spec{&ast.ValueSpec{Names: []*ast.Ident{{Name: "x"}}}},
	}
	got := indexTypeDecl(&types.Info{}, map[types.Object]bool{}, nil, decl)
	if got != nil {
		t.Fatalf("fieldDocs = %v, want nil", got)
	}
}

func TestExtractPackageSkipsNonNamedTypeName(t *testing.T) {
	fset := token.NewFileSet()
	file := fset.AddFile("b.go", -1, 20)
	file.SetLinesForContent([]byte("package m\n"))

	tpkg := types.NewPackage("m", "m")
	// TypeParam: IsAlias=false but Type() is not *Named.
	tn := types.NewTypeName(token.Pos(file.Base()), tpkg, "T", nil)
	_ = types.NewTypeParam(tn, types.NewInterfaceType(nil, nil))
	tpkg.Scope().Insert(tn)

	pkg := &packages.Package{
		PkgPath:   "m",
		Fset:      fset,
		Types:     tpkg,
		TypesInfo: &types.Info{},
		Syntax:    []*ast.File{{Name: &ast.Ident{Name: "m"}}},
	}
	out := extractPackage(pkg, extractorOptions{})
	if len(out.Types) != 0 {
		t.Fatalf("types = %+v, want none", out.Types)
	}
}

func TestSortedMethodsSkipsMissingDecls(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"m.go": `
package m
type T struct{}
func (t *T) M() {}
`,
	})
	cfg := &packages.Config{
		Dir:  dir,
		Mode: loadMode,
	}
	loaded, err := packages.Load(cfg, "./")
	if err != nil || len(loaded) == 0 || loaded[0].Types == nil {
		t.Fatalf("load: %v pkgs=%d", err, len(loaded))
	}
	pkg := loaded[0]
	tn, _ := pkg.Types.Scope().Lookup("T").(*types.TypeName)
	named, _ := tn.Type().(*types.Named)

	// Empty funcDecls → every method hits the !ok skip branch.
	got := sortedMethods(pkg.Fset, extractorOptions{}, nil, map[*types.Func]*ast.FuncDecl{}, named)
	if len(got) != 0 {
		t.Fatalf("sortedMethods = %d, want 0", len(got))
	}
}
