---
name: Go Lint
description: Run formatting and lint checks
runs:
  using: composite
  steps:
    - name: Prepare Go project
      uses: ./.github/actions/setup
      with:
        generate-proto: 'false'
    - name: Run CI checks
      shell: bash
      run: task ci
